// Auto-generated by photography/process_photos.py
const photoManifest = {
  "IMG_0577.jpg": {
    "month": "December",
    "year": 2025,
    "location": "Culberson County, Texas"
  },
  "IMG_0689.jpg": {
    "month": "December",
    "year": 2025,
    "location": "Carlsbad Caverns National Park, New Mexico"
  },
  "IMG_0702.jpg": {
    "month": "December",
    "year": 2021,
    "location": "San Francisco, California"
  },
  "IMG_0715.jpg": {
    "month": "December",
    "year": 2021,
    "location": "San Francisco, California"
  },
  "IMG_0901.jpg": {
    "month": "December",
    "year": 2025,
    "location": "Otero County, New Mexico"
  },
  "IMG_1404.jpg": {
    "month": "June",
    "year": 2025,
    "location": "Greater London, England"
  },
  "IMG_20190703_122935_Original.jpg": {
    "month": "July",
    "year": 2019,
    "location": "Rocky Mountain National Park, Colorado"
  },
  "IMG_2746.jpg": {
    "month": "April",
    "year": 2022,
    "location": "Fayette County, West Virginia"
  },
  "IMG_3668.jpg": {
    "month": "August",
    "year": 2026,
    "location": "Putrajaya"
  },
  "IMG_3958.jpg": {
    "month": "August",
    "year": 2026,
    "location": "Kuala Lumpur"
  },
  "IMG_4775.jpg": {
    "month": "January",
    "year": 2024,
    "location": "Kundah, Tamil Nadu"
  },
  "IMG_5650.jpg": {
    "month": "October",
    "year": 2022,
    "location": "Albemarle County, Virginia"
  },
  "IMG_6056.jpg": {
    "month": "May",
    "year": 2024,
    "location": "Newport, Rhode Island"
  },
  "IMG_7116.jpg": {
    "month": "December",
    "year": 2022,
    "location": "San Benito County, California"
  },
  "IMG_7119.jpg": {
    "month": "December",
    "year": 2022,
    "location": "San Benito County, California"
  },
  "IMG_7239.jpg": {
    "month": "July",
    "year": 2021,
    "location": "Augusta County, Virginia"
  },
  "IMG_7772.jpg": {
    "month": "July",
    "year": 2021,
    "location": "New York"
  },
  "IMG_7936.jpg": {
    "month": "July",
    "year": 2024,
    "location": "Cape Elizabeth, Maine"
  },
  "IMG_8290.jpg": {
    "month": "August",
    "year": 2021,
    "location": "Page County, Virginia"
  },
  "IMG_8401.jpg": {
    "month": "August",
    "year": 2024,
    "location": "Kochi, Kerala"
  },
  "IMG_9191.jpg": {
    "month": "September",
    "year": 2021,
    "location": "Virginia Beach, Virginia"
  },
  "IMG_9234.jpg": {
    "month": "May",
    "year": 2023,
    "location": "Miami, Florida"
  },
  "IMG_9398.jpg": {
    "month": "May",
    "year": 2023,
    "location": "Miami-Dade County, Florida"
  },
  "IMG_9453.jpg": {
    "month": "December",
    "year": 2024,
    "location": "Marin County, California"
  },
  "IMG_9490.jpg": {
    "month": "December",
    "year": 2024,
    "location": "Capitola, California"
  },
  "IMG_9520.jpg": {
    "month": "May",
    "year": 2023,
    "location": "Miami-Dade County, Florida"
  },
  "IMG_0040.jpg": {
    "month": "October",
    "year": 2019,
    "location": "Albemarle County, Virginia"
  },
  "IMG_0108.jpg": {
    "month": "November",
    "year": 2025,
    "location": "Riverside County, California"
  },
  "IMG_0126.jpg": {
    "month": "November",
    "year": 2025,
    "location": "Riverside County, California"
  },
  "IMG_0179.jpg": {
    "month": "November",
    "year": 2025,
    "location": "Riverside County, California"
  },
  "IMG_0298.jpg": {
    "month": "November",
    "year": 2025,
    "location": "Santa Barbara County, California"
  },
  "IMG_0334.jpg": {
    "month": "February",
    "year": 2025,
    "location": "Inyo County, California"
  },
  "IMG_0429.jpg": {
    "month": "February",
    "year": 2025,
    "location": "Inyo County, California"
  },
  "IMG_2837.jpg": {
    "month": "October",
    "year": 2023,
    "location": "Blount County, Tennessee"
  },
  "IMG_6570.jpg": {
    "month": "June",
    "year": 2021,
    "location": "Shenandoah County, Virginia"
  },
  "IMG_7616.jpg": {
    "month": "July",
    "year": 2024,
    "location": "Saint Louis, Missouri"
  },
  "IMG_4907.jpg": {
    "month": "February",
    "year": 2020,
    "location": "Charlottesville, Virginia"
  }
};
